### ISSUE TITLE
App loads only a small map area.

### ISSUE THREAD

**Issue by JSzut** [sothawo/mapjfx-demo#2]
Why does demo app map load only small parts and the loading lasts very long (my internet connection is fine)?

**Comment by sothawo** [comment]
I know this is a problem, please see this post: https://www.sothawo.com/2018/02/mapjfx-problems/
Alas there is nothing I can do at the moment, because is not reproducible.

**Comment by sothawo** [comment]
closing this as this is already in the library repo [https://github.com/sothawo/mapjfx/issues/29](https://github.com/sothawo/mapjfx/issues/29)
